<?php

declare(strict_types=1);

/*
 * Coretsia Framework (Monorepo)
 *
 * Project: Coretsia Framework (Monorepo)
 * Authors: Vladyslav Mudrichenko and contributors
 * Copyright (c) 2026 Vladyslav Mudrichenko
 *
 * SPDX-FileCopyrightText: 2026 Vladyslav Mudrichenko
 * SPDX-License-Identifier: Apache-2.0
 *
 * For contributors list, see git history.
 * See LICENSE and NOTICE in the project root for full license information.
 */

namespace Coretsia\Tools\Support;

final class ErrorCodes
{
    public const string CORETSIA_TOOLS_BOOTSTRAP_AUTOLOAD_MISSING = 'CORETSIA_TOOLS_BOOTSTRAP_AUTOLOAD_MISSING';
    public const string CORETSIA_TOOLS_IO_READ_FAILED = 'CORETSIA_TOOLS_IO_READ_FAILED';
    public const string CORETSIA_TOOLS_IO_WRITE_FAILED = 'CORETSIA_TOOLS_IO_WRITE_FAILED';
    public const string CORETSIA_REPO_TEXT_POLICY_VIOLATION = 'CORETSIA_REPO_TEXT_POLICY_VIOLATION';
    public const string CORETSIA_REPO_TEXT_POLICY_SCAN_FAILED = 'CORETSIA_REPO_TEXT_POLICY_SCAN_FAILED';
    public const string CORETSIA_TOOLKIT_DUP_GATE_SCAN_FAILED = 'CORETSIA_TOOLKIT_DUP_GATE_SCAN_FAILED';
    public const string CORETSIA_TOOLKIT_JSON_ENCODE_FORBIDDEN = 'CORETSIA_TOOLKIT_JSON_ENCODE_FORBIDDEN';
    public const string CORETSIA_TOOLKIT_DUPLICATION_DETECTED = 'CORETSIA_TOOLKIT_DUPLICATION_DETECTED';
    public const string CORETSIA_FINGERPRINT_SYMLINK_FORBIDDEN = 'CORETSIA_FINGERPRINT_SYMLINK_FORBIDDEN';
    public const string CORETSIA_TOOLS_INVALID_ARGUMENT_EXCEPTION_FORBIDDEN = 'CORETSIA_TOOLS_INVALID_ARGUMENT_EXCEPTION_FORBIDDEN';
    public const string CORETSIA_TOOLS_INVALID_ARGUMENT_EXCEPTION_GATE_SCAN_FAILED = 'CORETSIA_TOOLS_INVALID_ARGUMENT_EXCEPTION_GATE_SCAN_FAILED';
    public const string CORETSIA_JSON_FLOAT_FORBIDDEN = 'CORETSIA_JSON_FLOAT_FORBIDDEN';
    public const string CORETSIA_BUILD_ICONS_OUT_OF_DATE = 'CORETSIA_BUILD_ICONS_OUT_OF_DATE';
    public const string CORETSIA_BUILD_ICONS_FAILED = 'CORETSIA_BUILD_ICONS_FAILED';
    public const string CORETSIA_PACKAGE_INDEX_OUT_OF_DATE = 'CORETSIA_PACKAGE_INDEX_OUT_OF_DATE';
    public const string CORETSIA_PACKAGE_INDEX_FAILED = 'CORETSIA_PACKAGE_INDEX_FAILED';
    public const string CORETSIA_NEW_PACKAGE_FAILED = 'CORETSIA_NEW_PACKAGE_FAILED';
    public const string CORETSIA_PACKAGE_SCAFFOLD_OUT_OF_SYNC = 'CORETSIA_PACKAGE_SCAFFOLD_OUT_OF_SYNC';
    public const string CORETSIA_PACKAGE_SCAFFOLD_SYNC_FAILED = 'CORETSIA_PACKAGE_SCAFFOLD_SYNC_FAILED';
    public const string CORETSIA_RUNTIME_TOOLING_ARTIFACTS_VIOLATION = 'CORETSIA_RUNTIME_TOOLING_ARTIFACTS_VIOLATION';
    public const string CORETSIA_RUNTIME_TOOLING_ARTIFACTS_GATE_FAILED = 'CORETSIA_RUNTIME_TOOLING_ARTIFACTS_GATE_FAILED';
    public const string CORETSIA_PACKAGE_COMPLIANCE_VIOLATION = 'CORETSIA_PACKAGE_COMPLIANCE_VIOLATION';
    public const string CORETSIA_PACKAGE_COMPLIANCE_GATE_FAILED = 'CORETSIA_PACKAGE_COMPLIANCE_GATE_FAILED';
    public const string CORETSIA_PACKAGE_PUBLISH_SAFETY_VIOLATION = 'CORETSIA_PACKAGE_PUBLISH_SAFETY_VIOLATION';
    public const string CORETSIA_PACKAGE_PUBLISH_SAFETY_GATE_FAILED = 'CORETSIA_PACKAGE_PUBLISH_SAFETY_GATE_FAILED';
    public const string CORETSIA_RELEASE_LINE_WORKSPACE_SYNC_FAILED = 'CORETSIA_RELEASE_LINE_WORKSPACE_SYNC_FAILED';
    public const string CORETSIA_RELEASE_LINE_WORKSPACE_OUT_OF_SYNC = 'CORETSIA_RELEASE_LINE_WORKSPACE_OUT_OF_SYNC';
    public const string CORETSIA_RELEASE_LINE_PUBLIC_CONSTRAINTS_SYNC_FAILED = 'CORETSIA_RELEASE_LINE_PUBLIC_CONSTRAINTS_SYNC_FAILED';
    public const string CORETSIA_RELEASE_LINE_PUBLIC_CONSTRAINTS_OUT_OF_SYNC = 'CORETSIA_RELEASE_LINE_PUBLIC_CONSTRAINTS_OUT_OF_SYNC';
    public const string CORETSIA_DEPTRAC_OUT_OF_DATE = 'CORETSIA_DEPTRAC_OUT_OF_DATE';
    public const string CORETSIA_DEPTRAC_GENERATE_FAILED = 'CORETSIA_DEPTRAC_GENERATE_FAILED';
    public const string CORETSIA_DEPTRAC_SSOT_RULESET_MISSING = 'CORETSIA_DEPTRAC_SSOT_RULESET_MISSING';
    public const string CORETSIA_DEPTRAC_CYCLE_DETECTED = 'CORETSIA_DEPTRAC_CYCLE_DETECTED';
    public const string CORETSIA_DEPTRAC_ALLOWLIST_INVALID = 'CORETSIA_DEPTRAC_ALLOWLIST_INVALID';
    public const string CORETSIA_DEPTRAC_COMPOSER_EDGE_NOT_IN_SSOT = 'CORETSIA_DEPTRAC_COMPOSER_EDGE_NOT_IN_SSOT';
    public const string CORETSIA_CONFIG_DIRECTIVE_MIXED_LEVEL = 'CORETSIA_CONFIG_DIRECTIVE_MIXED_LEVEL';
    public const string CORETSIA_CONFIG_DIRECTIVE_TYPE_MISMATCH = 'CORETSIA_CONFIG_DIRECTIVE_TYPE_MISMATCH';
    public const string CORETSIA_CONFIG_RESERVED_NAMESPACE_USED = 'CORETSIA_CONFIG_RESERVED_NAMESPACE_USED';
    public const string CORETSIA_WORKSPACE_MANAGED_BLOCK_INVALID = 'CORETSIA_WORKSPACE_MANAGED_BLOCK_INVALID';
    public const string CORETSIA_WORKSPACE_MANAGED_REPOS_OUT_OF_SYNC = 'CORETSIA_WORKSPACE_MANAGED_REPOS_OUT_OF_SYNC';
    public const string CORETSIA_WORKSPACE_SYNC_FAILED = 'CORETSIA_WORKSPACE_SYNC_FAILED';
    public const string CORETSIA_PACKAGE_PHPUNIT_CONFIG_FORBIDDEN = 'CORETSIA_PACKAGE_PHPUNIT_CONFIG_FORBIDDEN';
    public const string CORETSIA_PACKAGE_PHPUNIT_CONFIG_GATE_FAILED = 'CORETSIA_PACKAGE_PHPUNIT_CONFIG_GATE_FAILED';
    public const string CORETSIA_NO_SKELETON_HTTP_DEFAULT_FORBIDDEN = 'CORETSIA_NO_SKELETON_HTTP_DEFAULT_FORBIDDEN';
    public const string CORETSIA_NO_SKELETON_HTTP_DEFAULT_GATE_FAILED = 'CORETSIA_NO_SKELETON_HTTP_DEFAULT_GATE_FAILED';
    public const string CORETSIA_NO_SKELETON_BUNDLES_DEFAULT_FORBIDDEN = 'CORETSIA_NO_SKELETON_BUNDLES_DEFAULT_FORBIDDEN';
    public const string CORETSIA_NO_SKELETON_BUNDLES_DEFAULT_GATE_FAILED = 'CORETSIA_NO_SKELETON_BUNDLES_DEFAULT_GATE_FAILED';
    public const string CORETSIA_NO_SKELETON_MODE_PRESETS_DEFAULT_FORBIDDEN = 'CORETSIA_NO_SKELETON_MODE_PRESETS_DEFAULT_FORBIDDEN';
    public const string CORETSIA_NO_SKELETON_MODE_PRESETS_DEFAULT_GATE_FAILED = 'CORETSIA_NO_SKELETON_MODE_PRESETS_DEFAULT_GATE_FAILED';
    public const string CORETSIA_NO_SKELETON_MODULES_DEFAULT_FORBIDDEN = 'CORETSIA_NO_SKELETON_MODULES_DEFAULT_FORBIDDEN';
    public const string CORETSIA_NO_SKELETON_MODULES_DEFAULT_GATE_FAILED = 'CORETSIA_NO_SKELETON_MODULES_DEFAULT_GATE_FAILED';
    public const string CORETSIA_CONTRACTS_ONLY_PORTS_FORBIDDEN = 'CORETSIA_CONTRACTS_ONLY_PORTS_FORBIDDEN';
    public const string CORETSIA_CONTRACTS_ONLY_PORTS_GATE_FAILED = 'CORETSIA_CONTRACTS_ONLY_PORTS_GATE_FAILED';
    public const string CORETSIA_RESERVED_TAGS_REGISTRY_DRIFT = 'CORETSIA_RESERVED_TAGS_REGISTRY_DRIFT';
    public const string CORETSIA_RESERVED_TAGS_REGISTRY_GATE_FAILED = 'CORETSIA_RESERVED_TAGS_REGISTRY_GATE_FAILED';
    public const string CORETSIA_OBSERVABILITY_NAMING_DRIFT = 'CORETSIA_OBSERVABILITY_NAMING_DRIFT';
    public const string CORETSIA_OBSERVABILITY_NAMING_GATE_FAILED = 'CORETSIA_OBSERVABILITY_NAMING_GATE_FAILED';
    public const string CORETSIA_OBSERVABILITY_SPAN_NAMING_DRIFT = 'CORETSIA_OBSERVABILITY_SPAN_NAMING_DRIFT';
    public const string CORETSIA_OBSERVABILITY_SPAN_NAMING_GATE_FAILED = 'CORETSIA_OBSERVABILITY_SPAN_NAMING_GATE_FAILED';
    public const string CORETSIA_OBSERVABILITY_METRIC_CATALOG_DRIFT = 'CORETSIA_OBSERVABILITY_METRIC_CATALOG_DRIFT';
    public const string CORETSIA_OBSERVABILITY_METRIC_CATALOG_GATE_FAILED = 'CORETSIA_OBSERVABILITY_METRIC_CATALOG_GATE_FAILED';
    public const string CORETSIA_ARTIFACT_HEADER_SCHEMA_DRIFT = 'CORETSIA_ARTIFACT_HEADER_SCHEMA_DRIFT';
    public const string CORETSIA_ARTIFACT_HEADER_SCHEMA_GATE_FAILED = 'CORETSIA_ARTIFACT_HEADER_SCHEMA_GATE_FAILED';
    public const string CORETSIA_CROSS_CUTTING_CONTRACT_DRIFT = 'CORETSIA_CROSS_CUTTING_CONTRACT_DRIFT';
    public const string CORETSIA_CROSS_CUTTING_CONTRACT_GATE_FAILED = 'CORETSIA_CROSS_CUTTING_CONTRACT_GATE_FAILED';
    public const string CORETSIA_KERNEL_PUBLIC_API_DRIFT = 'CORETSIA_KERNEL_PUBLIC_API_DRIFT';
    public const string CORETSIA_KERNEL_PUBLIC_API_GATE_FAILED = 'CORETSIA_KERNEL_PUBLIC_API_GATE_FAILED';
    public const string CORETSIA_DTO_GATE_FAILED = 'CORETSIA_DTO_GATE_FAILED';
    public const string CORETSIA_DTO_MARKER_VIOLATION = 'CORETSIA_DTO_MARKER_VIOLATION';
    public const string CORETSIA_DTO_NO_LOGIC_VIOLATION = 'CORETSIA_DTO_NO_LOGIC_VIOLATION';
    public const string CORETSIA_DTO_SHAPE_VIOLATION = 'CORETSIA_DTO_SHAPE_VIOLATION';
    public const string CORETSIA_DTO_GATE_SCAN_FAILED = 'CORETSIA_DTO_GATE_SCAN_FAILED';
    public const string CORETSIA_ATOMIC_WRITE_VIOLATION = 'CORETSIA_ATOMIC_WRITE_VIOLATION';
    public const string CORETSIA_ATOMIC_WRITE_GATE_FAILED = 'CORETSIA_ATOMIC_WRITE_GATE_FAILED';
    public const string CORETSIA_COMPOSER_AUDIT_FAILED = 'CORETSIA_COMPOSER_AUDIT_FAILED';
    public const string CORETSIA_TOOLS_NETWORK_FAILED = 'CORETSIA_TOOLS_NETWORK_FAILED';
    public const string CORETSIA_COMPOSER_AUDIT_SCAN_FAILED = 'CORETSIA_COMPOSER_AUDIT_SCAN_FAILED';
    public const string CORETSIA_SECRET_LEAK_DETECTED = 'CORETSIA_SECRET_LEAK_DETECTED';
    public const string CORETSIA_SECRET_GATE_SCAN_FAILED = 'CORETSIA_SECRET_GATE_SCAN_FAILED';
    public const string CORETSIA_DOC_VERSION_DRIFT = 'CORETSIA_DOC_VERSION_DRIFT';
    public const string CORETSIA_DOC_VERSION_GATE_FAILED = 'CORETSIA_DOC_VERSION_GATE_FAILED';
    public const string CORETSIA_LICENSE_HEADER_VIOLATION = 'CORETSIA_LICENSE_HEADER_VIOLATION';
    public const string CORETSIA_LICENSE_HEADER_GATE_FAILED = 'CORETSIA_LICENSE_HEADER_GATE_FAILED';

    /**
     * @var list<string>
     */
    private const array REGISTRY = [
        self::CORETSIA_TOOLS_BOOTSTRAP_AUTOLOAD_MISSING,
        self::CORETSIA_TOOLS_IO_READ_FAILED,
        self::CORETSIA_TOOLS_IO_WRITE_FAILED,
        self::CORETSIA_REPO_TEXT_POLICY_VIOLATION,
        self::CORETSIA_REPO_TEXT_POLICY_SCAN_FAILED,
        self::CORETSIA_TOOLKIT_DUP_GATE_SCAN_FAILED,
        self::CORETSIA_TOOLKIT_JSON_ENCODE_FORBIDDEN,
        self::CORETSIA_TOOLKIT_DUPLICATION_DETECTED,
        self::CORETSIA_FINGERPRINT_SYMLINK_FORBIDDEN,
        self::CORETSIA_TOOLS_INVALID_ARGUMENT_EXCEPTION_FORBIDDEN,
        self::CORETSIA_TOOLS_INVALID_ARGUMENT_EXCEPTION_GATE_SCAN_FAILED,
        self::CORETSIA_JSON_FLOAT_FORBIDDEN,
        self::CORETSIA_BUILD_ICONS_OUT_OF_DATE,
        self::CORETSIA_BUILD_ICONS_FAILED,
        self::CORETSIA_PACKAGE_INDEX_OUT_OF_DATE,
        self::CORETSIA_PACKAGE_INDEX_FAILED,
        self::CORETSIA_NEW_PACKAGE_FAILED,
        self::CORETSIA_PACKAGE_SCAFFOLD_OUT_OF_SYNC,
        self::CORETSIA_PACKAGE_SCAFFOLD_SYNC_FAILED,
        self::CORETSIA_RUNTIME_TOOLING_ARTIFACTS_VIOLATION,
        self::CORETSIA_RUNTIME_TOOLING_ARTIFACTS_GATE_FAILED,
        self::CORETSIA_PACKAGE_COMPLIANCE_VIOLATION,
        self::CORETSIA_PACKAGE_COMPLIANCE_GATE_FAILED,
        self::CORETSIA_PACKAGE_PUBLISH_SAFETY_VIOLATION,
        self::CORETSIA_PACKAGE_PUBLISH_SAFETY_GATE_FAILED,
        self::CORETSIA_RELEASE_LINE_WORKSPACE_SYNC_FAILED,
        self::CORETSIA_RELEASE_LINE_WORKSPACE_OUT_OF_SYNC,
        self::CORETSIA_RELEASE_LINE_PUBLIC_CONSTRAINTS_SYNC_FAILED,
        self::CORETSIA_RELEASE_LINE_PUBLIC_CONSTRAINTS_OUT_OF_SYNC,
        self::CORETSIA_DEPTRAC_OUT_OF_DATE,
        self::CORETSIA_DEPTRAC_GENERATE_FAILED,
        self::CORETSIA_DEPTRAC_SSOT_RULESET_MISSING,
        self::CORETSIA_DEPTRAC_CYCLE_DETECTED,
        self::CORETSIA_DEPTRAC_ALLOWLIST_INVALID,
        self::CORETSIA_DEPTRAC_COMPOSER_EDGE_NOT_IN_SSOT,
        self::CORETSIA_CONFIG_DIRECTIVE_MIXED_LEVEL,
        self::CORETSIA_CONFIG_DIRECTIVE_TYPE_MISMATCH,
        self::CORETSIA_CONFIG_RESERVED_NAMESPACE_USED,
        self::CORETSIA_WORKSPACE_MANAGED_BLOCK_INVALID,
        self::CORETSIA_WORKSPACE_MANAGED_REPOS_OUT_OF_SYNC,
        self::CORETSIA_WORKSPACE_SYNC_FAILED,
        self::CORETSIA_PACKAGE_PHPUNIT_CONFIG_FORBIDDEN,
        self::CORETSIA_PACKAGE_PHPUNIT_CONFIG_GATE_FAILED,
        self::CORETSIA_NO_SKELETON_HTTP_DEFAULT_FORBIDDEN,
        self::CORETSIA_NO_SKELETON_HTTP_DEFAULT_GATE_FAILED,
        self::CORETSIA_NO_SKELETON_BUNDLES_DEFAULT_FORBIDDEN,
        self::CORETSIA_NO_SKELETON_BUNDLES_DEFAULT_GATE_FAILED,
        self::CORETSIA_NO_SKELETON_MODE_PRESETS_DEFAULT_FORBIDDEN,
        self::CORETSIA_NO_SKELETON_MODE_PRESETS_DEFAULT_GATE_FAILED,
        self::CORETSIA_NO_SKELETON_MODULES_DEFAULT_FORBIDDEN,
        self::CORETSIA_NO_SKELETON_MODULES_DEFAULT_GATE_FAILED,
        self::CORETSIA_CONTRACTS_ONLY_PORTS_FORBIDDEN,
        self::CORETSIA_CONTRACTS_ONLY_PORTS_GATE_FAILED,
        self::CORETSIA_RESERVED_TAGS_REGISTRY_DRIFT,
        self::CORETSIA_RESERVED_TAGS_REGISTRY_GATE_FAILED,
        self::CORETSIA_OBSERVABILITY_NAMING_DRIFT,
        self::CORETSIA_OBSERVABILITY_NAMING_GATE_FAILED,
        self::CORETSIA_OBSERVABILITY_SPAN_NAMING_DRIFT,
        self::CORETSIA_OBSERVABILITY_SPAN_NAMING_GATE_FAILED,
        self::CORETSIA_OBSERVABILITY_METRIC_CATALOG_DRIFT,
        self::CORETSIA_OBSERVABILITY_METRIC_CATALOG_GATE_FAILED,
        self::CORETSIA_ARTIFACT_HEADER_SCHEMA_DRIFT,
        self::CORETSIA_ARTIFACT_HEADER_SCHEMA_GATE_FAILED,
        self::CORETSIA_CROSS_CUTTING_CONTRACT_DRIFT,
        self::CORETSIA_CROSS_CUTTING_CONTRACT_GATE_FAILED,
        self::CORETSIA_KERNEL_PUBLIC_API_DRIFT,
        self::CORETSIA_KERNEL_PUBLIC_API_GATE_FAILED,
        self::CORETSIA_DTO_GATE_FAILED,
        self::CORETSIA_DTO_MARKER_VIOLATION,
        self::CORETSIA_DTO_NO_LOGIC_VIOLATION,
        self::CORETSIA_DTO_SHAPE_VIOLATION,
        self::CORETSIA_DTO_GATE_SCAN_FAILED,
        self::CORETSIA_ATOMIC_WRITE_VIOLATION,
        self::CORETSIA_ATOMIC_WRITE_GATE_FAILED,
        self::CORETSIA_COMPOSER_AUDIT_FAILED,
        self::CORETSIA_TOOLS_NETWORK_FAILED,
        self::CORETSIA_COMPOSER_AUDIT_SCAN_FAILED,
        self::CORETSIA_SECRET_LEAK_DETECTED,
        self::CORETSIA_SECRET_GATE_SCAN_FAILED,
        self::CORETSIA_DOC_VERSION_DRIFT,
        self::CORETSIA_DOC_VERSION_GATE_FAILED,
        self::CORETSIA_LICENSE_HEADER_VIOLATION,
        self::CORETSIA_LICENSE_HEADER_GATE_FAILED,
    ];

    /**
     * @var array<string, true>|null
     */
    private static ?array $lookup = null;

    /**
     * @var list<string>|null
     */
    private static ?array $sorted = null;

    private function __construct()
    {
    }

    public static function has(string $code): bool
    {
        self::initialize();

        return isset(self::$lookup[$code]);
    }

    /**
     * @return list<string> Sorted ascending by byte-order (strcmp).
     */
    public static function all(): array
    {
        self::initialize();

        /** @var list<string> $sorted */
        $sorted = self::$sorted;

        return $sorted;
    }

    private static function initialize(): void
    {
        if (self::$lookup !== null && self::$sorted !== null) {
            return;
        }

        $codes = self::REGISTRY;

        $unique = \array_values(\array_unique($codes));
        if (\count($unique) !== \count($codes)) {
            throw new \LogicException('error-codes-registry-contains-duplicates');
        }

        \usort(
            $codes,
            static fn (string $a, string $b): int => \strcmp($a, $b),
        );

        $lookup = [];
        foreach ($codes as $code) {
            $lookup[$code] = true;
        }

        self::$sorted = $codes;
        self::$lookup = $lookup;
    }
}
