<?php

declare(strict_types=1);

/*
 * Coretsia Framework (Monorepo)
 *
 * Project: Coretsia Framework (Monorepo)
 * Authors: Vladyslav Mudrichenko and contributors
 * Copyright (c) 2026 Vladyslav Mudrichenko
 *
 * SPDX-FileCopyrightText: 2026 Vladyslav Mudrichenko
 * SPDX-License-Identifier: Apache-2.0
 *
 * For contributors list, see git history.
 * See LICENSE and NOTICE in the project root for full license information.
 */

namespace Coretsia\Kernel\Tests\Integration;

use Coretsia\Contracts\Observability\CorrelationIdProviderInterface;
use Coretsia\Foundation\Context\ContextKeys;
use Coretsia\Foundation\Context\ContextStore;
use Coretsia\Foundation\Id\CorrelationIdGenerator;
use Coretsia\Foundation\Id\IdGeneratorInterface;
use Coretsia\Foundation\Id\UlidGenerator;
use Coretsia\Foundation\Observability\Metrics\NoopMeter;
use Coretsia\Foundation\Observability\Tracing\NoopTracer;
use Coretsia\Foundation\Provider\Tags as FoundationTags;
use Coretsia\Foundation\Runtime\Reset\ResetOrchestrator;
use Coretsia\Foundation\Tag\TagRegistry;
use Coretsia\Foundation\Time\Stopwatch;
use Coretsia\Kernel\Runtime\Hook\HookInvoker;
use Coretsia\Kernel\Runtime\KernelRuntime;
use Coretsia\Kernel\Runtime\UnitOfWorkType;
use PHPUnit\Framework\TestCase;
use Psr\Container\ContainerInterface;
use Psr\Log\NullLogger;

final class KernelRuntimeUsesCorrelationSourcesAndDefaultIdGeneratorTest extends TestCase
{
    public function testCorrelationIdComesFromProviderWhenAvailable(): void
    {
        $contextStore = new ContextStore();

        $runtime = self::runtime(
            contextStore: $contextStore,
            uowIds: new KernelRuntimeUsesCorrelationSourcesIdGenerator(
                '01ARZ3NDEKTSV4RRFFQ69G5FAV',
            ),
            correlationIdProvider: new KernelRuntimeUsesCorrelationSourcesCorrelationIdProvider(
                '01B7X3NDEKTSV4RRFFQ69G5FAV',
            ),
        );

        $context = $runtime->beginUnitOfWork(UnitOfWorkType::HTTP);

        self::assertSame(
            '01B7X3NDEKTSV4RRFFQ69G5FAV',
            $context['correlationId'],
        );
        self::assertSame(
            '01B7X3NDEKTSV4RRFFQ69G5FAV',
            $contextStore->get(ContextKeys::CORRELATION_ID),
        );

        self::assertSame(
            '01ARZ3NDEKTSV4RRFFQ69G5FAV',
            $context['uowId'],
        );
        self::assertSame(
            '01ARZ3NDEKTSV4RRFFQ69G5FAV',
            $contextStore->get(ContextKeys::UOW_ID),
        );
    }

    public function testCorrelationIdFallsBackToCorrelationIdGeneratorWhenProviderReturnsNull(): void
    {
        $contextStore = new ContextStore();

        $runtime = self::runtime(
            contextStore: $contextStore,
            uowIds: new KernelRuntimeUsesCorrelationSourcesIdGenerator(
                '01ARZ3NDEKTSV4RRFFQ69G5FAV',
            ),
            correlationIdProvider: new KernelRuntimeUsesCorrelationSourcesCorrelationIdProvider(null),
        );

        $context = $runtime->beginUnitOfWork(UnitOfWorkType::HTTP);

        self::assertIsString($context['correlationId']);
        self::assertMatchesRegularExpression(
            '/\A[0-9A-HJKMNP-TV-Z]{26}\z/',
            $context['correlationId'],
        );

        self::assertSame(
            $context['correlationId'],
            $contextStore->get(ContextKeys::CORRELATION_ID),
        );

        /*
         * Correlation ids are generated by CorrelationIdGenerator, not by the
         * default Foundation IdGeneratorInterface used for uow_id.
         */
        self::assertNotSame(
            '01ARZ3NDEKTSV4RRFFQ69G5FAV',
            $context['correlationId'],
        );

        self::assertSame(
            '01ARZ3NDEKTSV4RRFFQ69G5FAV',
            $context['uowId'],
        );
        self::assertSame(
            '01ARZ3NDEKTSV4RRFFQ69G5FAV',
            $contextStore->get(ContextKeys::UOW_ID),
        );
    }

    public function testUowIdComesFromDefaultFoundationIdGenerator(): void
    {
        $contextStore = new ContextStore();

        $runtime = self::runtime(
            contextStore: $contextStore,
            uowIds: new KernelRuntimeUsesCorrelationSourcesIdGenerator(
                '01ARZ3NDEKTSV4RRFFQ69G5FAV',
            ),
            correlationIdProvider: new KernelRuntimeUsesCorrelationSourcesCorrelationIdProvider(
                '01B7X3NDEKTSV4RRFFQ69G5FAV',
            ),
        );

        $context = $runtime->beginUnitOfWork(UnitOfWorkType::HTTP);

        self::assertSame(
            '01ARZ3NDEKTSV4RRFFQ69G5FAV',
            $context['uowId'],
        );
        self::assertSame(
            '01ARZ3NDEKTSV4RRFFQ69G5FAV',
            $contextStore->get(ContextKeys::UOW_ID),
        );

        self::assertSame(
            '01B7X3NDEKTSV4RRFFQ69G5FAV',
            $context['correlationId'],
        );
        self::assertSame(
            '01B7X3NDEKTSV4RRFFQ69G5FAV',
            $contextStore->get(ContextKeys::CORRELATION_ID),
        );
    }

    private static function runtime(
        ContextStore $contextStore,
        IdGeneratorInterface $uowIds,
        CorrelationIdProviderInterface $correlationIdProvider,
    ): KernelRuntime {
        return new KernelRuntime(
            contextStore: $contextStore,
            resetOrchestrator: self::resetOrchestrator($contextStore),
            stopwatch: new Stopwatch(),
            uowIds: $uowIds,
            correlationIdProvider: $correlationIdProvider,
            correlationIds: new CorrelationIdGenerator(new UlidGenerator()),
            hooks: new HookInvoker(
                container: new KernelRuntimeUsesCorrelationSourcesContainer([]),
                tags: new TagRegistry(),
            ),
            logger: new NullLogger(),
            tracer: new NoopTracer(),
            meter: new NoopMeter(),
        );
    }

    private static function resetOrchestrator(ContextStore $contextStore): ResetOrchestrator
    {
        $tagRegistry = new TagRegistry();

        $tagRegistry->add(
            FoundationTags::KERNEL_RESET,
            ContextStore::class,
        );

        return new ResetOrchestrator(
            container: new KernelRuntimeUsesCorrelationSourcesContainer([
                ContextStore::class => $contextStore,
            ]),
            tagRegistry: $tagRegistry,
        );
    }
}

final readonly class KernelRuntimeUsesCorrelationSourcesIdGenerator implements IdGeneratorInterface
{
    /**
     * @param non-empty-string $id
     */
    public function __construct(
        private string $id,
    ) {
    }

    public function generate(): string
    {
        return $this->id;
    }
}

final readonly class KernelRuntimeUsesCorrelationSourcesCorrelationIdProvider implements CorrelationIdProviderInterface
{
    /**
     * @param non-empty-string|null $correlationId
     */
    public function __construct(
        private ?string $correlationId,
    ) {
    }

    public function correlationId(): ?string
    {
        return $this->correlationId;
    }
}

final readonly class KernelRuntimeUsesCorrelationSourcesContainer implements ContainerInterface
{
    /**
     * @param array<string, mixed> $services
     */
    public function __construct(
        private array $services,
    ) {
    }

    public function get(string $id): mixed
    {
        if (!$this->has($id)) {
            throw new \RuntimeException('test-container-service-not-found');
        }

        return $this->services[$id];
    }

    public function has(string $id): bool
    {
        return \array_key_exists($id, $this->services);
    }
}
