<?php

declare(strict_types=1);

/*
 * Coretsia Framework (Monorepo)
 *
 * Project: Coretsia Framework (Monorepo)
 * Authors: Vladyslav Mudrichenko and contributors
 * Copyright (c) 2026 Vladyslav Mudrichenko
 *
 * SPDX-FileCopyrightText: 2026 Vladyslav Mudrichenko
 * SPDX-License-Identifier: Apache-2.0
 *
 * For contributors list, see git history.
 * See LICENSE and NOTICE in the project root for full license information.
 */

namespace Coretsia\Tools\Spikes\_support;

final class ErrorCodes
{
    public const string CORETSIA_DETERMINISM_GIT_REQUIRED = 'CORETSIA_DETERMINISM_GIT_REQUIRED';
    public const string CORETSIA_DETERMINISM_WORKTREE_DIRTY = 'CORETSIA_DETERMINISM_WORKTREE_DIRTY';
    public const string CORETSIA_DETERMINISM_RERUN_FAILED = 'CORETSIA_DETERMINISM_RERUN_FAILED';

    public const string CORETSIA_SPIKES_BOOTSTRAP_AUTOLOAD_MISSING = 'CORETSIA_SPIKES_BOOTSTRAP_AUTOLOAD_MISSING';
    public const string CORETSIA_SPIKES_FIXTURE_PATH_INVALID = 'CORETSIA_SPIKES_FIXTURE_PATH_INVALID';
    public const string CORETSIA_SPIKES_OUTPUT_BYPASS_DETECTED = 'CORETSIA_SPIKES_OUTPUT_BYPASS_DETECTED';
    public const string CORETSIA_SPIKES_OUTPUT_GATE_SCAN_FAILED = 'CORETSIA_SPIKES_OUTPUT_GATE_SCAN_FAILED';
    public const string CORETSIA_SPIKES_IO_READ_FAILED = 'CORETSIA_SPIKES_IO_READ_FAILED';
    public const string CORETSIA_SPIKES_IO_WRITE_FAILED = 'CORETSIA_SPIKES_IO_WRITE_FAILED';
    public const string CORETSIA_SPIKES_IO_POLICY_VIOLATION = 'CORETSIA_SPIKES_IO_POLICY_VIOLATION';
    public const string CORETSIA_SPIKES_IO_POLICY_GATE_SCAN_FAILED = 'CORETSIA_SPIKES_IO_POLICY_GATE_SCAN_FAILED';
    public const string CORETSIA_SPIKES_BOUNDARY_FORBIDDEN_IMPORT = 'CORETSIA_SPIKES_BOUNDARY_FORBIDDEN_IMPORT';
    public const string CORETSIA_SPIKES_BOUNDARY_FORBIDDEN_PATH = 'CORETSIA_SPIKES_BOUNDARY_FORBIDDEN_PATH';
    public const string CORETSIA_SPIKES_BOUNDARY_SCAN_FAILED = 'CORETSIA_SPIKES_BOUNDARY_SCAN_FAILED';
    public const string CORETSIA_SPIKES_CANONICAL_PATHS_VIOLATION = 'CORETSIA_SPIKES_CANONICAL_PATHS_VIOLATION';
    public const string CORETSIA_SPIKES_CANONICAL_PATHS_GATE_SCAN_FAILED = 'CORETSIA_SPIKES_CANONICAL_PATHS_GATE_SCAN_FAILED';

    public const string CORETSIA_REPO_TEXT_POLICY_VIOLATION = 'CORETSIA_REPO_TEXT_POLICY_VIOLATION';
    public const string CORETSIA_REPO_TEXT_POLICY_SCAN_FAILED = 'CORETSIA_REPO_TEXT_POLICY_SCAN_FAILED';

    public const string CORETSIA_TOOLKIT_DUP_GATE_SCAN_FAILED = 'CORETSIA_TOOLKIT_DUP_GATE_SCAN_FAILED';
    public const string CORETSIA_TOOLKIT_JSON_ENCODE_FORBIDDEN = 'CORETSIA_TOOLKIT_JSON_ENCODE_FORBIDDEN';
    public const string CORETSIA_TOOLKIT_DUPLICATION_DETECTED = 'CORETSIA_TOOLKIT_DUPLICATION_DETECTED';

    public const string CORETSIA_FINGERPRINT_SYMLINK_FORBIDDEN = 'CORETSIA_FINGERPRINT_SYMLINK_FORBIDDEN';
    public const string CORETSIA_FINGERPRINT_REPO_ROOT_INVALID = 'CORETSIA_FINGERPRINT_REPO_ROOT_INVALID';
    public const string CORETSIA_FINGERPRINT_TRACKED_ENV_ALLOWLIST_INVALID = 'CORETSIA_FINGERPRINT_TRACKED_ENV_ALLOWLIST_INVALID';
    public const string CORETSIA_FINGERPRINT_TRACKED_ENV_ALLOWLIST_NOT_SORTED = 'CORETSIA_FINGERPRINT_TRACKED_ENV_ALLOWLIST_NOT_SORTED';
    public const string CORETSIA_FINGERPRINT_TRACKED_ENV_ALLOWLIST_DUPLICATE = 'CORETSIA_FINGERPRINT_TRACKED_ENV_ALLOWLIST_DUPLICATE';
    public const string CORETSIA_FINGERPRINT_HASH_FAILED = 'CORETSIA_FINGERPRINT_HASH_FAILED';
    public const string CORETSIA_FINGERPRINT_RESULT_INVALID = 'CORETSIA_FINGERPRINT_RESULT_INVALID';
    public const string CORETSIA_FINGERPRINT_JSON_ENCODE_FAILED = 'CORETSIA_FINGERPRINT_JSON_ENCODE_FAILED';

    public const string CORETSIA_FINGERPRINT_EXPLAIN_REPO_ROOT_INVALID = 'CORETSIA_FINGERPRINT_EXPLAIN_REPO_ROOT_INVALID';
    public const string CORETSIA_FINGERPRINT_EXPLAIN_INPUT_INVALID = 'CORETSIA_FINGERPRINT_EXPLAIN_INPUT_INVALID';
    public const string CORETSIA_FINGERPRINT_EXPLAIN_DUPLICATE_NORMALIZED_PATH = 'CORETSIA_FINGERPRINT_EXPLAIN_DUPLICATE_NORMALIZED_PATH';
    public const string CORETSIA_FINGERPRINT_EXPLAIN_DOTENV_META_REQUIRED = 'CORETSIA_FINGERPRINT_EXPLAIN_DOTENV_META_REQUIRED';
    public const string CORETSIA_FINGERPRINT_EXPLAIN_INVALID_SHA256 = 'CORETSIA_FINGERPRINT_EXPLAIN_INVALID_SHA256';

    public const string CORETSIA_TOOLS_INVALID_ARGUMENT_EXCEPTION_FORBIDDEN = 'CORETSIA_TOOLS_INVALID_ARGUMENT_EXCEPTION_FORBIDDEN';
    public const string CORETSIA_TOOLS_INVALID_ARGUMENT_EXCEPTION_GATE_SCAN_FAILED = 'CORETSIA_TOOLS_INVALID_ARGUMENT_EXCEPTION_GATE_SCAN_FAILED';

    public const string CORETSIA_JSON_FLOAT_FORBIDDEN = 'CORETSIA_JSON_FLOAT_FORBIDDEN';
    public const string CORETSIA_PAYLOAD_JSON_ENCODE_FAILED = 'CORETSIA_PAYLOAD_JSON_ENCODE_FAILED';

    public const string CORETSIA_DEPTRAC_CYCLE_DETECTED = 'CORETSIA_DEPTRAC_CYCLE_DETECTED';
    public const string CORETSIA_DEPTRAC_ALLOWLIST_INVALID = 'CORETSIA_DEPTRAC_ALLOWLIST_INVALID';
    public const string CORETSIA_DEPTRAC_GRAPH_ARTIFACT_INVALID = 'CORETSIA_DEPTRAC_GRAPH_ARTIFACT_INVALID';

    public const string CORETSIA_CONFIG_DIRECTIVE_MIXED_LEVEL = 'CORETSIA_CONFIG_DIRECTIVE_MIXED_LEVEL';
    public const string CORETSIA_CONFIG_DIRECTIVE_TYPE_MISMATCH = 'CORETSIA_CONFIG_DIRECTIVE_TYPE_MISMATCH';
    public const string CORETSIA_CONFIG_RESERVED_NAMESPACE_USED = 'CORETSIA_CONFIG_RESERVED_NAMESPACE_USED';
    public const string CORETSIA_CONFIG_EXPLAINER_INPUT_INVALID = 'CORETSIA_CONFIG_EXPLAINER_INPUT_INVALID';
    public const string CORETSIA_CONFIG_MERGER_INPUT_INVALID = 'CORETSIA_CONFIG_MERGER_INPUT_INVALID';
    public const string CORETSIA_CONFIG_MERGER_RESULT_INVALID = 'CORETSIA_CONFIG_MERGER_RESULT_INVALID';

    public const string CORETSIA_WORKSPACE_MANAGED_BLOCK_INVALID = 'CORETSIA_WORKSPACE_MANAGED_BLOCK_INVALID';
    public const string CORETSIA_WORKSPACE_BACKUP_PATH_MISSING = 'CORETSIA_WORKSPACE_BACKUP_PATH_MISSING';
    public const string CORETSIA_WORKSPACE_COMPOSER_JSON_PARSE_FAILED = 'CORETSIA_WORKSPACE_COMPOSER_JSON_PARSE_FAILED';
    public const string CORETSIA_WORKSPACE_COMPOSER_JSON_ENCODE_FAILED = 'CORETSIA_WORKSPACE_COMPOSER_JSON_ENCODE_FAILED';
    public const string CORETSIA_WORKSPACE_PACKAGE_COMPOSER_SCHEMA_INVALID = 'CORETSIA_WORKSPACE_PACKAGE_COMPOSER_SCHEMA_INVALID';
    public const string CORETSIA_WORKSPACE_SYNC_RESULT_INVALID = 'CORETSIA_WORKSPACE_SYNC_RESULT_INVALID';

    public const string CORETSIA_PACKAGE_PHPUNIT_CONFIG_FORBIDDEN = 'CORETSIA_PACKAGE_PHPUNIT_CONFIG_FORBIDDEN';
    public const string CORETSIA_PACKAGE_PHPUNIT_CONFIG_GATE_FAILED = 'CORETSIA_PACKAGE_PHPUNIT_CONFIG_GATE_FAILED';

    /**
     * @var list<string>
     */
    private const array REGISTRY = [
        self::CORETSIA_DETERMINISM_GIT_REQUIRED,
        self::CORETSIA_DETERMINISM_WORKTREE_DIRTY,
        self::CORETSIA_DETERMINISM_RERUN_FAILED,

        self::CORETSIA_SPIKES_BOOTSTRAP_AUTOLOAD_MISSING,
        self::CORETSIA_SPIKES_FIXTURE_PATH_INVALID,
        self::CORETSIA_SPIKES_OUTPUT_BYPASS_DETECTED,
        self::CORETSIA_SPIKES_OUTPUT_GATE_SCAN_FAILED,
        self::CORETSIA_SPIKES_IO_READ_FAILED,
        self::CORETSIA_SPIKES_IO_WRITE_FAILED,
        self::CORETSIA_SPIKES_IO_POLICY_VIOLATION,
        self::CORETSIA_SPIKES_IO_POLICY_GATE_SCAN_FAILED,
        self::CORETSIA_SPIKES_BOUNDARY_FORBIDDEN_IMPORT,
        self::CORETSIA_SPIKES_BOUNDARY_FORBIDDEN_PATH,
        self::CORETSIA_SPIKES_BOUNDARY_SCAN_FAILED,
        self::CORETSIA_SPIKES_CANONICAL_PATHS_VIOLATION,
        self::CORETSIA_SPIKES_CANONICAL_PATHS_GATE_SCAN_FAILED,

        self::CORETSIA_REPO_TEXT_POLICY_VIOLATION,
        self::CORETSIA_REPO_TEXT_POLICY_SCAN_FAILED,

        self::CORETSIA_TOOLKIT_DUP_GATE_SCAN_FAILED,
        self::CORETSIA_TOOLKIT_JSON_ENCODE_FORBIDDEN,
        self::CORETSIA_TOOLKIT_DUPLICATION_DETECTED,

        self::CORETSIA_FINGERPRINT_SYMLINK_FORBIDDEN,
        self::CORETSIA_FINGERPRINT_REPO_ROOT_INVALID,
        self::CORETSIA_FINGERPRINT_TRACKED_ENV_ALLOWLIST_INVALID,
        self::CORETSIA_FINGERPRINT_TRACKED_ENV_ALLOWLIST_NOT_SORTED,
        self::CORETSIA_FINGERPRINT_TRACKED_ENV_ALLOWLIST_DUPLICATE,
        self::CORETSIA_FINGERPRINT_HASH_FAILED,
        self::CORETSIA_FINGERPRINT_RESULT_INVALID,
        self::CORETSIA_FINGERPRINT_JSON_ENCODE_FAILED,
        self::CORETSIA_FINGERPRINT_EXPLAIN_REPO_ROOT_INVALID,
        self::CORETSIA_FINGERPRINT_EXPLAIN_INPUT_INVALID,
        self::CORETSIA_FINGERPRINT_EXPLAIN_DUPLICATE_NORMALIZED_PATH,
        self::CORETSIA_FINGERPRINT_EXPLAIN_DOTENV_META_REQUIRED,
        self::CORETSIA_FINGERPRINT_EXPLAIN_INVALID_SHA256,

        self::CORETSIA_TOOLS_INVALID_ARGUMENT_EXCEPTION_FORBIDDEN,
        self::CORETSIA_TOOLS_INVALID_ARGUMENT_EXCEPTION_GATE_SCAN_FAILED,

        self::CORETSIA_JSON_FLOAT_FORBIDDEN,
        self::CORETSIA_PAYLOAD_JSON_ENCODE_FAILED,

        self::CORETSIA_DEPTRAC_CYCLE_DETECTED,
        self::CORETSIA_DEPTRAC_ALLOWLIST_INVALID,
        self::CORETSIA_DEPTRAC_GRAPH_ARTIFACT_INVALID,

        self::CORETSIA_CONFIG_DIRECTIVE_MIXED_LEVEL,
        self::CORETSIA_CONFIG_DIRECTIVE_TYPE_MISMATCH,
        self::CORETSIA_CONFIG_RESERVED_NAMESPACE_USED,
        self::CORETSIA_CONFIG_EXPLAINER_INPUT_INVALID,
        self::CORETSIA_CONFIG_MERGER_INPUT_INVALID,
        self::CORETSIA_CONFIG_MERGER_RESULT_INVALID,

        self::CORETSIA_WORKSPACE_MANAGED_BLOCK_INVALID,
        self::CORETSIA_WORKSPACE_BACKUP_PATH_MISSING,
        self::CORETSIA_WORKSPACE_COMPOSER_JSON_PARSE_FAILED,
        self::CORETSIA_WORKSPACE_COMPOSER_JSON_ENCODE_FAILED,
        self::CORETSIA_WORKSPACE_PACKAGE_COMPOSER_SCHEMA_INVALID,
        self::CORETSIA_WORKSPACE_SYNC_RESULT_INVALID,

        self::CORETSIA_PACKAGE_PHPUNIT_CONFIG_FORBIDDEN,
        self::CORETSIA_PACKAGE_PHPUNIT_CONFIG_GATE_FAILED,
    ];

    /**
     * @var array<string, true>|null
     */
    private static ?array $lookup = null;

    /**
     * @var list<string>|null
     */
    private static ?array $sorted = null;

    private function __construct()
    {
    }

    public static function has(string $code): bool
    {
        self::initialize();

        return isset(self::$lookup[$code]);
    }

    /**
     * @return list<string> Sorted ascending by byte-order (strcmp).
     */
    public static function all(): array
    {
        self::initialize();

        /** @var list<string> $sorted */
        $sorted = self::$sorted;

        return $sorted;
    }

    private static function initialize(): void
    {
        if (self::$lookup !== null && self::$sorted !== null) {
            return;
        }

        $codes = self::REGISTRY;

        $unique = \array_values(\array_unique($codes));
        if (\count($unique) !== \count($codes)) {
            throw new \LogicException('error-codes-registry-contains-duplicates');
        }

        \usort(
            $codes,
            static fn(string $a, string $b): int => \strcmp($a, $b),
        );

        $lookup = [];
        foreach ($codes as $code) {
            $lookup[$code] = true;
        }

        self::$sorted = $codes;
        self::$lookup = $lookup;
    }
}
