<?php

declare(strict_types=1);

/*
 * Coretsia Framework (Monorepo)
 *
 * Project: Coretsia Framework (Monorepo)
 * Authors: Vladyslav Mudrichenko and contributors
 * Copyright (c) 2026 Vladyslav Mudrichenko
 *
 * SPDX-FileCopyrightText: 2026 Vladyslav Mudrichenko
 * SPDX-License-Identifier: Apache-2.0
 *
 * For contributors list, see git history.
 * See LICENSE and NOTICE in the project root for full license information.
 */

namespace Coretsia\Contracts\Database;

/**
 * Contracts-level SQL dialect boundary.
 *
 * This interface exposes a narrow vendor-neutral dialect port for future
 * database runtime packages, database driver packages, migration runtime
 * packages, and query compiler owners.
 *
 * The dialect boundary exists for common SQL portability differences such as
 * logical dialect identity, identifier quoting, boolean literal rendering,
 * limit/offset syntax, returning support, identity/autogenerated column
 * support, and transactional DDL support.
 *
 * This interface MUST NOT be treated as a full SQL compiler, SQL parser, query
 * builder, schema builder, expression model, grammar model, vendor platform
 * object, Doctrine platform adapter, PDO wrapper, or database implementation.
 *
 * SQL identifiers and generated SQL fragments are sensitive by default.
 * Runtime owners must apply redaction policy before any logging, tracing,
 * metrics, health output, CLI output, error descriptor extension, migration
 * output, or unsafe debug output.
 */
interface SqlDialectInterface
{
    /**
     * Returns the logical dialect id.
     *
     * The returned id must be stable, deterministic, lowercase ASCII, and match:
     *
     * ^[a-z][a-z0-9_-]*$
     *
     * The dialect id is not a PHP extension name, class name, vendor object
     * name, Doctrine platform name, PDO driver name, or platform service id.
     *
     * @return non-empty-string
     */
    public function id(): string;

    /**
     * Quotes one SQL identifier according to dialect-owned rules.
     *
     * The input is a single identifier, not a compound SQL fragment and not a
     * generic SQL escaping surface. Schema-qualified names, table-qualified
     * names, wildcard expressions, aliases, expressions, and raw SQL fragments
     * are compiler-owned concerns.
     *
     * The input identifier and returned SQL-adjacent string are sensitive by
     * default and MUST NOT be exposed through unsafe diagnostics by default.
     *
     * @param non-empty-string $identifier
     * @return non-empty-string
     */
    public function quoteIdentifier(string $identifier): string;

    /**
     * Returns the dialect-specific SQL literal for a boolean value.
     *
     * The returned string is SQL text and MUST be treated as SQL-adjacent data.
     * Runtime owners must not expose it through unsafe diagnostics by default.
     *
     * @return non-empty-string
     */
    public function booleanLiteral(bool $value): string;

    /**
     * Applies dialect-specific limit/offset syntax to an existing query.
     *
     * This method is intentionally narrow. It exists because limit/offset syntax
     * differs across SQL dialects and is required by real database integrations.
     *
     * Implementations MUST preserve existing binding order. If the dialect
     * needs additional bindings for limit or offset, those bindings MUST be
     * appended in placeholder order.
     *
     * Limit and offset values are optional non-negative integers. When both are
     * null, implementations SHOULD return an equivalent query.
     *
     * Unsupported combinations may be rejected by implementation-owned
     * exceptions, but those exceptions MUST NOT expose raw SQL by default.
     *
     * @param int<0,max>|null $limit
     * @param int<0,max>|null $offset
     */
    public function applyLimitOffset(
        SqlQueryInterface $query,
        ?int $limit = null,
        ?int $offset = null,
    ): SqlQueryInterface;

    /**
     * Returns whether this dialect supports a native SQL returning clause for
     * relevant write operations according to owner-defined semantics.
     */
    public function supportsReturning(): bool;

    /**
     * Returns whether this dialect supports identity or autogenerated column
     * behavior according to owner-defined schema and migration semantics.
     */
    public function supportsIdentityColumns(): bool;

    /**
     * Returns whether DDL statements can normally be executed transactionally
     * according to owner-defined dialect semantics.
     */
    public function supportsTransactionalDdl(): bool;
}
