<?php

declare(strict_types=1);

/*
 * Coretsia Framework (Monorepo)
 *
 * Project: Coretsia Framework (Monorepo)
 * Authors: Vladyslav Mudrichenko and contributors
 * Copyright (c) 2026 Vladyslav Mudrichenko
 *
 * SPDX-FileCopyrightText: 2026 Vladyslav Mudrichenko
 * SPDX-License-Identifier: Apache-2.0
 *
 * For contributors list, see git history.
 * See LICENSE and NOTICE in the project root for full license information.
 */

namespace Coretsia\Tools\Spikes\deptrac\tests;

use Coretsia\Tools\Spikes\deptrac\DeptracGenerate;
use PHPUnit\Framework\TestCase;

final class DeptracYamlIsDeterministicAndSafeTest extends TestCase
{
    public function testGenerateYamlFromFixtureIsRerunNoDiffAndLfOnly(): void
    {
        $first = DeptracGenerate::generateYamlFromFixture('deptrac_min/package_index_ok.php');
        $second = DeptracGenerate::generateYamlFromFixture('deptrac_min/package_index_ok.php');

        self::assertSame($first, $second, 'rerun => no diff (string bytes)');

        $this->assertLfOnlyAndFinalNewline($first);
    }

    public function testGeneratedYamlContainsNoAbsolutePathPatternsAndNoBackslashes(): void
    {
        $yaml = DeptracGenerate::generateYamlFromFixture('deptrac_min/package_index_ok.php');

        $this->assertLfOnlyAndFinalNewline($yaml);

        // Basic shape sanity (avoid “empty output” regressions).
        self::assertStringContainsString("# GENERATED by Coretsia spikes (Epic 0.80.0) - DO NOT EDIT.\n", $yaml);
        self::assertStringContainsString("# fixture: deptrac_min/package_index_ok.php\n", $yaml);
        self::assertStringContainsString("deptrac:\n", $yaml);
        self::assertStringContainsString("  paths:\n", $yaml);
        self::assertStringContainsString("  layers:\n", $yaml);
        self::assertStringContainsString("  ruleset:\n", $yaml);

        // Hard ban: no CR anywhere.
        self::assertFalse(str_contains($yaml, "\r"), 'must be LF-only (no CR)');

        // Hard ban: identifiers/paths MUST NOT contain backslashes.
        self::assertFalse(str_contains($yaml, "\\"), 'must not contain backslashes');

        // Safety: MUST NOT contain URL-like tokens (reduce accidental leaks).
        self::assertFalse(str_contains($yaml, '://'), 'must not contain URL-like tokens');

        // Absolute path patterns:
        self::assertDoesNotMatchRegularExpression('~/(?:home|users)/~i', $yaml, 'contains POSIX home absolute pattern');
        self::assertDoesNotMatchRegularExpression('~(?i)\b[A-Z]:[\\\\/]~', $yaml, 'contains Windows drive absolute pattern');
        self::assertDoesNotMatchRegularExpression('~\\\\\\\\[^\\\\/]+[\\\\/][^\\\\/]+~', $yaml, 'contains UNC absolute pattern');
        self::assertDoesNotMatchRegularExpression('~//[^/]+/[^/]+~', $yaml, 'contains UNC-like //server/share pattern');
    }

    private function assertLfOnlyAndFinalNewline(string $text): void
    {
        self::assertNotSame('', $text, 'must not be empty');
        self::assertFalse(str_contains($text, "\r"), 'must be LF-only (no CR)');
        self::assertSame("\n", substr($text, -1), 'must end with final newline');
    }
}
